version: "3.8"

services:
  youtube-dj:
    build:
      context: .
    
    container_name: youtube-dj
    restart: unless-stopped
    
    ports:
      - "${WEB_PORT:-8800}:3000"     # 웹 애플리케이션 포트
      - "${SOCKET_PORT:-8801}:3001"   # 소켓 서버 포트
    
    environment:
      - NODE_ENV=production
      # WiFi QR코드용 환경변수
      - WIFI_SSID=${WIFI_SSID:-}
      - WIFI_PASSWORD=${WIFI_PASSWORD:-}
      - WIFI_SECURITY=${WIFI_SECURITY:-WPA}
    
    env_file:
      - .env
    
    # 헬스체크 설정
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 로그 설정
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# 네트워크 설정 (선택사항)
networks:
  default:
    name: youtube-dj-network
    driver: bridge

# 볼륨 설정 (선택사항 - 데이터 지속성이 필요한 경우)
# volumes:
#   youtube-dj-data:
#     driver: local
