version: "3.8"

services:
  youtube-dj:
    # 사전 빌드된 이미지 사용
    image: ${REGISTRY:-registry.hwida.com}/${IMAGE_NAME:-youtube-dj}:${TAG:-latest}
    
    container_name: youtube-dj
    restart: unless-stopped
    
    ports:
      - "${WEB_PORT:-3000}:3000"     # 웹 애플리케이션 포트
      - "${SOCKET_PORT:-3001}:3001"   # 소켓 서버 포트
    
    environment:
      # 런타임 환경변수
      - NODE_ENV=production
      - NEXT_PUBLIC_SOCKET_URL=${SOCKET_URL:-http://localhost:3001}
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SOCKET_SERVER_PORT=${SOCKET_SERVER_PORT:-3001}
    
    # 환경변수 파일 로드 (있는 경우)
    env_file:
      - .env
    
    # 헬스체크 설정
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # 로그 설정
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# 네트워크 설정
networks:
  default:
    name: youtube-dj-network
    driver: bridge
