version: "3.8"

services:
  youtube-dj:
    build:
      context: .
      args:
        NEXT_PUBLIC_SOCKET_URL: http://192.168.0.9:3001
    image: registry.hwida.com/youtube-dj:latest
    container_name: youtube-dj
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SOCKET_URL=http://192.168.0.9:3001
    # 필요시 환경변수, 볼륨, 네트워크 등 추가 가능 